/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DiscordMessages {
    /**
    * Whether to use compact mode or not.
    */
    'compactMode': boolean;
    /**
    * Whether to use light theme or not.
    */
    'lightTheme': boolean;
  }
}

declare global {


  interface HTMLDiscordMessagesElement extends Components.DiscordMessages, HTMLStencilElement {}
  var HTMLDiscordMessagesElement: {
    prototype: HTMLDiscordMessagesElement;
    new (): HTMLDiscordMessagesElement;
  };
  interface HTMLElementTagNameMap {
    'discord-messages': HTMLDiscordMessagesElement;
  }
}

declare namespace LocalJSX {
  interface DiscordMessages {
    /**
    * Whether to use compact mode or not.
    */
    'compactMode'?: boolean;
    /**
    * Whether to use light theme or not.
    */
    'lightTheme'?: boolean;
  }

  interface IntrinsicElements {
    'discord-messages': DiscordMessages;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'discord-messages': LocalJSX.DiscordMessages & JSXBase.HTMLAttributes<HTMLDiscordMessagesElement>;
    }
  }
}


