/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  DiscordTimestamp,
} from './util';

export namespace Components {
  interface DiscordMention {
    /**
    * The color to use for this mention. Only works for role mentions and must be in hex format.
    */
    'color': string;
    /**
    * Whether this entire message block should be highlighted (to emulate the "logged in user" being pinged).
    */
    'highlight': boolean;
    /**
    * The name of the user, channel, or role to mention. If omitted, it will be set based upon the `type` prop (i.e. 'User', 'channel', or 'Role').
    */
    'name'?: string;
    /**
    * The type of mention this should be. This will prepend the proper prefix character. Valid values: `user`, `channel`, `role`
    */
    'type': string;
  }
  interface DiscordMessage {
    /**
    * The message author's username.
    */
    'author': string;
    /**
    * The message author's avatar. Can be a relative path or external link.
    */
    'avatar': string;
    /**
    * Whether the message author is a bot or not.
    */
    'bot': boolean;
    /**
    * Whether the message has been edited or not.
    */
    'edited': boolean;
    /**
    * The message author's primary role color. Can be any [CSS color value](https://www.w3schools.com/cssref/css_colors_legal.asp).
    */
    'roleColor': string;
    /**
    * The timestamp to use for the message date. When supplying a string, the format must be `01/31/2000`.
    */
    'timestamp': DiscordTimestamp;
  }
  interface DiscordMessages {
    /**
    * Whether to use compact mode or not.
    */
    'compactMode': boolean;
    /**
    * Whether to use light theme or not.
    */
    'lightTheme': boolean;
  }
}

declare global {


  interface HTMLDiscordMentionElement extends Components.DiscordMention, HTMLStencilElement {}
  var HTMLDiscordMentionElement: {
    prototype: HTMLDiscordMentionElement;
    new (): HTMLDiscordMentionElement;
  };

  interface HTMLDiscordMessageElement extends Components.DiscordMessage, HTMLStencilElement {}
  var HTMLDiscordMessageElement: {
    prototype: HTMLDiscordMessageElement;
    new (): HTMLDiscordMessageElement;
  };

  interface HTMLDiscordMessagesElement extends Components.DiscordMessages, HTMLStencilElement {}
  var HTMLDiscordMessagesElement: {
    prototype: HTMLDiscordMessagesElement;
    new (): HTMLDiscordMessagesElement;
  };
  interface HTMLElementTagNameMap {
    'discord-mention': HTMLDiscordMentionElement;
    'discord-message': HTMLDiscordMessageElement;
    'discord-messages': HTMLDiscordMessagesElement;
  }
}

declare namespace LocalJSX {
  interface DiscordMention {
    /**
    * The color to use for this mention. Only works for role mentions and must be in hex format.
    */
    'color'?: string;
    /**
    * Whether this entire message block should be highlighted (to emulate the "logged in user" being pinged).
    */
    'highlight'?: boolean;
    /**
    * The name of the user, channel, or role to mention. If omitted, it will be set based upon the `type` prop (i.e. 'User', 'channel', or 'Role').
    */
    'name'?: string;
    /**
    * The type of mention this should be. This will prepend the proper prefix character. Valid values: `user`, `channel`, `role`
    */
    'type'?: string;
  }
  interface DiscordMessage {
    /**
    * The message author's username.
    */
    'author'?: string;
    /**
    * The message author's avatar. Can be a relative path or external link.
    */
    'avatar'?: string;
    /**
    * Whether the message author is a bot or not.
    */
    'bot'?: boolean;
    /**
    * Whether the message has been edited or not.
    */
    'edited'?: boolean;
    /**
    * The message author's primary role color. Can be any [CSS color value](https://www.w3schools.com/cssref/css_colors_legal.asp).
    */
    'roleColor'?: string;
    /**
    * The timestamp to use for the message date. When supplying a string, the format must be `01/31/2000`.
    */
    'timestamp'?: DiscordTimestamp;
  }
  interface DiscordMessages {
    /**
    * Whether to use compact mode or not.
    */
    'compactMode'?: boolean;
    /**
    * Whether to use light theme or not.
    */
    'lightTheme'?: boolean;
  }

  interface IntrinsicElements {
    'discord-mention': DiscordMention;
    'discord-message': DiscordMessage;
    'discord-messages': DiscordMessages;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'discord-mention': LocalJSX.DiscordMention & JSXBase.HTMLAttributes<HTMLDiscordMentionElement>;
      'discord-message': LocalJSX.DiscordMessage & JSXBase.HTMLAttributes<HTMLDiscordMessageElement>;
      'discord-messages': LocalJSX.DiscordMessages & JSXBase.HTMLAttributes<HTMLDiscordMessagesElement>;
    }
  }
}


